### PR TITLE
Update to upstream 0.21

### PR DESCRIPTION
**Pull request by dcaliste**
While looking into the update branch for sailfishos/gawk, it seems that an update to 0.20.2 was necessary.

I'm proposing such an update here, and since at it, another to latest 0.21. @mlehtima, @mkosola and @xfade what do you think ? Do you agree with the PR or do you prefer to stay for the moment at 0.20.2 since 0.21 is still young ?

### CODE REVIEW

**Comment by dcaliste** [comment]
I forgot to update the archive.dir.tar.xz file...

**Comment by mlehtima** [comment]
One thing I noticed is that you could also update the submodule urls to sailfishos-mirror github, another thing is that the code fails to build with error "cp: cannot create regular file 'libtextstyle/build-aux/': Not a directory"

**Comment by Thaodan** [comment]
> I forgot to update the archive.dir.tar.xz file...

Can you remove that and checkin the sources of that directory? Having binaries in git is not good.

**Comment by dcaliste** [comment]
> another thing is that the code fails to build with error "cp: cannot create regular file 'libtextstyle/build-aux/': Not a directory"

Oops sorry, indeed, I didn't notice it since that directory was created by earlier build attempts. Thanks, it's fixed now.

**Comment by dcaliste** [comment]
> One thing I noticed is that you could also update the submodule urls to sailfishos-mirror github

Good point, done.

**Comment by dcaliste** [comment]
> Can you remove that and checkin the sources of that directory? Having binaries in git is not good.

Well, it's to avoid a `wget` done by the `autogen.sh` of gettext. The target of the wget is not in git as far as I can tell.

We don't have wget, so I'm patching the `autogen.sh` to use `curl` instead. I'm testing and will update if it is successful.

**Comment by Thaodan** [comment]
> > Can you remove that and checkin the sources of that directory? Having binaries in git is not good.
> 
> Well, it's to avoid a `wget` done by the `autogen.sh` of gettext. The target of the wget is not in git as far as I can tell.
> 
> We don't have wget, so I'm patching the `autogen.sh` to use `curl` instead. I'm testing and will update if it is successful.

That doesn't work, there is no network  during builder.
You can achieve a similar workaround by downloading them manually (write a script and put it into rpm/) and then copying them into the builddir.
See here:
https://github.com/sailfishos/grep/blob/master/rpm/gnu-grep.spec#L92

**Comment by dcaliste** [comment]
Thanks @Thaodan for the tips. There is just one thing I don't understand : what is running `posync.sh` actually ?

**Comment by Thaodan** [comment]
> Thanks @Thaodan for the tips. There is just one thing I don't understand : what is running `posync.sh` actually ?

The person updating the package.

**Comment by dcaliste** [comment]
I've pushed a new version, updating the URLs for submodules, and correcting the failing `cp` in spec.

I've added an additional commit also to have the `archive.dir.tar.xz` downloaded by a script. I'm not sure I get it right though. @thaodan, are we supposed to keep the downloaded binary kept in the git repo here ?

**Comment by mlehtima** [comment]
I think we should not make this overly complicated. Now the package fails to build again because that archive.dir.tar.xz is missing. I personally think we should just keep that file in the repo like have done before.

**Comment by Thaodan** [comment]
> I've pushed a new version, updating the URLs for submodules, and correcting the failing `cp` in spec.
> 
> I've added an additional commit also to have the `archive.dir.tar.xz` downloaded by a script. I'm not sure I get it right though. @Thaodan, are we supposed to keep the downloaded binary kept in the git repo here ?

Currently we have the archive.tar. in the repo, if we instead extract the context of the archive into the tree the diff is better when we change something.

https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=gettext-tools/misc/Makefile.am;h=87fa7806b10a2797413c343296f9f8892a2fcbd6;hb=HEAD#l73

**Comment by dcaliste** [comment]
Ok, I understand (or I think I do). So I've unpacked the `archive.dir.tar.xz` and versioned the result text files, I've created a script (`getArchive.sh`) to get it and unpack it, and I've modified the spec file to recreate the tar in the `%prep` from the sources.

I must admit that I find it a bit overkill also, particularly because the unpacked version of `archive.dir.tar.xz` contains a lot of files (> 3400). So it's in a separated third commit. @Thaodan and @mlehtima , I let you decide if you want the third commit or not.

**Comment by mlehtima** [comment]
I still think unpacking the archive is overkill and only makes things more complicated without bringing any obvious benefit. It's also possible that with unpacked archive future updates could have huge diff depending on how often/much the files in the archive change.

**Comment by pvuorela** [comment]
Woah, the 43 different versions of gettext source dirs under rpm/ is definitely too much here.

**Comment by dcaliste** [comment]
Ok, so I get this as a demand for third commit removal ; )

Done. There's now only the upgrade to 0.20.2 in this PR, without creating the archive tar.gz ourselves but just uploading it as a binary.

**Comment by pvuorela** [comment]
Seems good to me and builds fine in OBS.

**Comment by Thaodan** [comment]
I looked into how archive.tar is generated and from what I've read its just 
expanded for each new version released.
Because of this its fine for me that we store the binary it git.
The only questionmark I have is the why since the archive contains files for 
each version released.

**Comment by pvuorela** [comment]
Yea it's a strange file, but then again it's a file available from upstream and relatively small. And the updates here are relatively rare anyway, this being the third version update. Some of the gnu stuff are slightly painful to compile from git and whatever gets it done simple enough is good for me.

**Comment by Thaodan** [comment]
> Some of the gnu stuff are slightly painful
> to compile from git and whatever gets it done simple enough is good for me.
> 

Yes stuff like this is still wip from what I read upstream:
https://alpha.gnu.org/gnu/gettext/haible-gettext-2020.pdf

**Comment by dcaliste** [comment]
> The only questionmark I have is the why since the archive contains files for
each version released.

If I remember correctly, it's for `autoreconf`. I don't know why exactly all previous versions are needed, but maybe you can force a version with `autoreconf` ?

**Review by pvuorela — APPROVED** [review]

**Pull request merged**
